# Generated by Django 4.1 on 2022-08-04 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(max_length=10, unique=True)),
            ],
            options={
                "ordering": ["label"],
            },
        ),
        migrations.AlterModelOptions(
            name="post",
            options={"ordering": ["data"]},
        ),
        migrations.AddField(
            model_name="post",
            name="tags",
            field=models.ManyToManyField(to="posts.tag"),
        ),
    ]
