# Generated by Django 4.1.5 on 2023-01-03 23:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0003_blog_comentario"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Blog",
        ),
        migrations.RemoveField(
            model_name="post",
            name="autor",
        ),
        migrations.AlterField(
            model_name="tag",
            name="label",
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
