# Generated by Django 5.1.1 on 2024-09-20 17:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Equipes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=25, unique=True)),
                ("jogadores", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Jogador",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="Modalidade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=20)),
                ("min_jogadores", models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name="Jogadores_em_equipes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "equipe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="jogos.equipes",
                        to_field="nome",
                    ),
                ),
                (
                    "jogador",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="jogos.jogador"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="jogador",
            name="equipes",
            field=models.ManyToManyField(
                through="jogos.Jogadores_em_equipes", to="jogos.equipes"
            ),
        ),
        migrations.AddField(
            model_name="equipes",
            name="modalidade",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="jogos.modalidade"
            ),
        ),
    ]
