# Generated by Django 5.1.1 on 2024-09-20 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jogos", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="modalidade",
            name="categoria",
            field=models.CharField(
                choices=[("M", "Masculino"), ("F", "Feminino"), ("MT", "Misto")],
                default="MT",
                max_length=2,
            ),
        ),
        migrations.AddField(
            model_name="modalidade",
            name="tipo",
            field=models.CharField(
                choices=[("I", "Individual"), ("C", "Coletivo")],
                default="I",
                max_length=1,
            ),
        ),
    ]
