# Generated by Django 5.1.1 on 2024-09-20 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="genero",
            field=models.CharField(default="n", max_length=1, verbose_name="genero"),
        ),
    ]
