# Generated by Django 5.1.1 on 2024-09-20 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0002_user_genero"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="genero",
            field=models.CharField(
                choices=[("M", "Masculino"), ("F", "Feminino"), ("I", "Indefinido")],
                default="I",
                max_length=1,
                verbose_name="genero",
            ),
        ),
    ]
