name: Django CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
env:
  DEBUG: 'true'
  SECRET_KEY: '123456'
  EMAIL_HOST: 'smtp.mail.com'
  EMAIL_PORT: '587'
  EMAIL_HOST_USER: 'your@mail.com'
  EMAIL_HOST_PASSWORD: 'app_password'
  DEFAULT_FROM_EMAIL: 'a@nother.mail'

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: ["3.10"]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Tests
      run: |
        python src/manage.py test
